name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Node.jsのセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: 依存関係のインストール
        run: npm ci
      - name: コンパイル
        run: npm run compile
      - name: テスト実行
        run: npm test
      - name: リント実行
        run: npm run lint
